### ISSUE TITLE
rebase `Java8` with `master`

### ISSUE THREAD

**Issue by nono303** [telemaxx/mapsforgesrv#30]
Hi @telemaxx, @JFritzle,

As said in #28 & #29, Java8 branch as a lot of difference with master that might had been forgetting to be merged.
`git diff master..origin/Java8` : [git_diff_master..Java8.patch](https://github.com/telemaxx/mapsforgesrv/files/8177113/git_diff_master.Java8.txt)

The Most delicate - in my point of view and not to mention the typo or small changes - is the usage of two different package for servlet (`jakarta.servlet` & `javax.servlet`)

I think it would be interesting to correctly rebase Java8 with common parts of master branch and then have a look on a possible single branch with multiple SDK target builds with gradle (see https://stackoverflow.com/questions/56526194/using-multiple-library-with-different-sdk-version-in-android-studio). 
It would be really easier to make PR and ensure changes are backpacked to all target SDK!

**Comment by JFritzle** [comment]
Unfortunately, jakarta.servlet is not compatible with Eclipse 2020-06, last Eclipse version working with Java 8.

**Comment by nono303** [comment]
the IDE JRE runtime and Project SDK version are independent
I use latest Eclipse (2021-12) running with openjdk 17.0.2 an also have JRE 1.8 installed (not as Eclipse runtime)
> In mapsforgesrv eclipse project properties > Java Build Path > Libraries : add Library > JRE System Library > Alternate JRE and select java 1.8 ;)

Also jakarta.servlet are not in JRE package but in https://mvnrepository.com/artifact/org.eclipse.jetty.toolchain/jetty-jakarta-servlet-api depends on jetty 11.x. You can try to add it explicitely on Java8 `build.gradle`

**Comment by telemaxx** [comment]
Java 8 branch got a last version.
Now developing continues only at "task" and "master" branch
