### ISSUE TITLE
Tile requests from GpsPrune fail with IOException

### ISSUE THREAD

**Issue by activityworkshop** [telemaxx/mapsforgesrv#36]
Originated from Sourceforge: https://sourceforge.net/p/prune-gps/discussion/682167/thread/3ce6661934/ because you asked for a Github issue to be raised here for tracking.

I don't know whether the fix for this problem will end up on the GpsPrune side or on the Mapsforgesrv side. The good news is that it's very reproducible. When I run Mapsforgesrv locally on port 8080, requests from Firefox and from wget are all successful, delivering a png image.  When GpsPrune requests similar tiles, the server appears to generate the image but then throws an IOException "I/O error writing PNG file!" when flushing to the output stream.  So it appears that the requests from GpsPrune are somehow different.  GpsPrune is however able to get tiles from openstreetmap and countless other tile providers without this issue.

**Comment by telemaxx** [comment]
Download Link (1,8MB small !):
https://activityworkshop.net/software/gpsprune/download.html

Wireshark Mytourbook:
![grafik](https://user-images.githubusercontent.com/22706487/170871445-bb917e12-6e7f-418d-837b-ddbb18dfd04f.png)

Wireshark gpsprune:
![grafik](https://user-images.githubusercontent.com/22706487/170871552-e9383f0a-df69-4f8d-adb4-0cbeaea077fd.png)


Ended red, reason?

**Comment by activityworkshop** [comment]
From what I can tell, GpsPrune doesn't like the way the response is opened.
wget tells me that the response looks like this:
 > Content-Type: image/png
 > Transfer-Encoding: chunked
 > Length: unspecified [image/png]

which of course makes sense from the server side.  But then GpsPrune receives this open connection and asks for conn.getContentLength() which gives back -1 (presumably meaning unspecified).  With all its other map servers this content length gives the number of bytes in the response, or <=0 if it's invalid.  Therefore GpsPrune assumes that there aren't any bytes to load and closes the connection.  Then the server tries to write the stream (I think the size is still unknown at this point) and can't because the connection has been closed from the other side - hence IOException "Broken pipe".

If you can point me towards the source of "Mytourbook" then I can have a look what they do differently with the connection.

**Comment by telemaxx** [comment]
i have not written the map2 part, but i think it is here:
https://github.com/mytourbook/mytourbook/blob/e65e48a3f02d523e3a169a5bf4d1f69b799423fc/bundles/net.tourbook/src/de/byteholder/geoclipse/map/TileImageLoader.java#L146

When i add in line 161:
System.out.println("##### URL: " + mp.getOnlineMapUrl() + tile.toString());

i get outputs when map is moved.

![grafik](https://user-images.githubusercontent.com/22706487/170883625-3053bbc7-53f9-42d1-891e-1e95222ca03a.png)

**Comment by telemaxx** [comment]
with MyTourBook i see also sometimes the same exception for some tiles.

**Comment by activityworkshop** [comment]
If GpsPrune is happy with a -1 tile size and just takes as many bytes as it can until it gets -1, then the tile images are all displayed fine (and also cached locally), so I'll close this issue.  I'll put the fix in the next release.
Thanks for the help.

**Comment by telemaxx** [comment]
i am impressed how much functionality you put in 1.8MByte. This is really amazing!

**Comment by activityworkshop** [comment]
Haha - thanks very much!
It was a sad day when it grew too big to fit on a floppy disk :/
