### ISSUE TITLE
TCP port already in use 

### ISSUE THREAD

**Issue by mff73** [telemaxx/mapsforgesrv#41]
### What happened?

hello,
i use a lot this project for MyTourbook usage, and i faced twice this issue of TCP port already in use.
![image](https://user-images.githubusercontent.com/50132146/197487123-a0b5424c-9403-40ba-ad97-1847949bb7ee.png)
i looked into some windows settings, and didn't find anything.

Thus i tried to find another port, which was working for some weeks, and again, it seems to be "blocked"
![image](https://user-images.githubusercontent.com/50132146/197487022-13e77980-ec5f-4047-8ba8-c8d208ad4e45.png)

I use it on my professional computer, thus, with corporate tools for security, maybe a clue to help me find a solution ? 

### Version

Java 11 Branch(Default)

**Comment by nono303** [comment]
hi @mff73 
This message is not a mapsforgesrv bug.
It indicate that another Windows process is listening on this port
To know which process is, just exec `netstat -n -o` find the process listening on the TCP port, kill the process and then launch mapsforgesrv again

**Comment by JFritzle** [comment]
Message `TCP port 'nnnnn' already in use` **might** be erroneous and should better be called `TCP port 'nnnnn' not available`.

In order to check if TCP port is really in use, open _Command Prompt_ window and run command `netstat -a`.
If port 60000 at localhost is already in use, you will notice output like that:
```
C:\Users\username>netstat -a

Active Connections

  Proto  Local Address          Foreign Address        State
  ...
  TCP    127.0.0.1:60000        hostname:0             LISTENING
  ...
```
If port 60000 is not in use, something else might be the cause.
Open _Command Prompt_ window and start Tcl interpreter by command `"C:\Program Files\Tcl\bin\tclsh.exe"`.  
At Tcl command prompt `%` enter following 2 Tcl commands:
```
catch {socket -server {} -myaddr 127.0.0.1 60000} msg
puts "$msg"
```
First Tcl command will return 0 or 1 whether port 60000 is available or not available.
If port is not available, second command shows the error message returned by operating system.

**Comment by JFritzle** [comment]
Latest [Mapsforge-for-MyTourbook](https://github.com/JFritzle/Mapsforge-for-MyTourbook) version now shows corresponding operating system message in case of failure.

**Comment by mff73** [comment]
hi everyone, thanks for your answers.
Sorry to have tagged it as a bug, i was almost sure it was on the computer itself and needed help to know what.
i restarted it, and finally, initial port was working "again", so all is working now, without clear root cause. i keep your explanations for next time ;) thanks.

**Comment by mff73** [comment]
Hello everyone,
I have updated to latest versions, and i am still facing sometimes this TCP issue.
It is on my professional computer though, which is connected internet over lots of """gateways"""", etc... (not an expert).
What is really strange : when configured with default port 60815, and issue is raising, i switch to 60000 and it is working, and a few days later, this 60000 is "bugging" and switching back to 60815 work "again".
here is today screen.
![image](https://user-images.githubusercontent.com/50132146/204989261-6d5b3439-9d60-4a02-a947-bb75768d9886.png)

according to your advices above, it seems ports are not used by other process but ....

What do you think, please ?
Sorry for this small issue, surely due to my computer.

**Comment by JFritzle** [comment]
An issue reported [here](https://github.com/docker/for-win/issues/3171) describes a similar problem, where
- a specific TCP port is not available to an application
- neither command `netstat -a` nor powershell's `Get-NetTCPConnection` show anything about this port 

The author however found out, that port was excluded for whatever reason:
 `netsh interface ipv4 show excludedportrange protocol=tcp`
  
And indeed, when I try to use a port \<port\> out of excluded port ranges by running command
`socket -server {}  -myaddr 127.0.0.1 <port>`
in a Tcl `tclsh.exe` or Wish `wish.exe` shell, I exactly get same error message
`couldn't open socket: invalid argument`
Maybe the same is happening to ports at your site?  If not, I'm sorry, I have no more ideas.

Issue report above and [this article](https://stackoverflow.com/questions/54010365/how-to-see-what-is-reserving-ephemeral-port-ranges-on-windows) tell about solving the problem by using setting dynamic port ranges.

**Comment by mff73** [comment]
Hello,
thanks. It is just to complicated for me 😁
i will leave with it, and changing ports when needed. no worries.
Thanks.

**Comment by JFritzle** [comment]
Long story short:  
`couldn't open socket: invalid argument` error message tells, although the port is currently not in use, it is currently excluded by Windows operating system (not by Mapsforge tile server!) from common use for whatever reason. There is no simple solution other than to find and use another working port.
