### ISSUE TITLE
Mapsforge Tile Version unknown

### ISSUE THREAD

**Issue by Ilpredatore** [telemaxx/mapsforgesrv#46]
### Contact Details

federico.boscarato@gmail.com

### What happened?

Hi,
i'm trying to start mapsforgesrv-fatjar.jar, but i have the following error:

![image](https://github.com/telemaxx/mapsforgesrv/assets/22062353/72a80521-d33b-45be-b7cd-c74ed12b7b55)

I downloaded:
[0.19.0 for java11: latest mapsforge 0.19 libs](https://github.com/telemaxx/mapsforgesrv/releases/tag/v0.19.0_for_java_11)
how i can resolve?

thank you very much.

Federico

### Version

Java 11 Branch(Default)

**Comment by telemaxx** [comment]
Hi Federico,
sure that you have copied the jar to the correct folder which is configured in the Mapsforge-for-QMapShack.ini File?
The Line looks like this:

`set server_jar    "C:/Program Files/MapsforgeSrv/mapsforgesrv-fatjar.jar"`

Can you check what you see when you click on "Configure Server"

Thomas

**Comment by JFritzle** [comment]
Hi Federico,

Unfortunately, this message was shown too whenever Java trying to run tile server's JAR file ended abnormally.
Java always ends abnormally, when JAR file has been compiled for a newer Java version than the Java version being used.

I am able to reproduce the same error message as shown when using mapsforgesrv-fatjar.jar with Java runtime older than Java version 11. This is because mapsforgesrv-fatjar.jar has been cpmpiled for Java version 11. However, no error was encountered when trying mapsforgesrv-fatjar.jar with Java runtime version 11.0.1 and newer.

I just updated the Mapsforge-for-QMapShack.tcl file. Now, abnormal end of Java gets caught and Java's error message gets shown. Please retry.

Jürgen

**Comment by Ilpredatore** [comment]
Hello,
i checked java version, it is

![image](https://github.com/telemaxx/mapsforgesrv/assets/22062353/f5a0ab94-13ea-4993-b7de-7a7df69ccc05)

i update Mapsforge-for-QMapShack.tcl file with the last one and now the new error is:

![image](https://github.com/telemaxx/mapsforgesrv/assets/22062353/3fe5aed8-9d5c-4fe3-8faf-9b527485aed9)


Federico

**Comment by JFritzle** [comment]
I am sorry, but I am not able to reproduce abnormal exit with Java runtime 11.0.18.

Please check MD5 hash of your downloaded JAR file: 
`certutil -hashfile <path-to-your-mapsforgesrv-fatjar.jar> MD5`
MD5 hash in my environment is 0727bd3d73ffcd1ae0c6f9f72379795d

Please check your Java executable from command line:
`java -version`
Output of my freshly downloaded Java SE 11.0.18 is
```
java version "11.0.18" 2023-01-17 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.18+9-LTS-195)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.18+9-LTS-195, mixed mode)
```

Please check from command line
`java -jar <path-to-your-mapsforgesrv-fatjar.jar> -h`
```
Output in my environment is
2023-06-01 09:16:01.983 MapsforgeSrv - a mapsforge tile server. version: 0.19.0
2023-06-01 09:16:01.987 Java runtime version: 11.0.18
usage: mapsforgesrv
 -c,--config <arg>                   Config file overriding cmd line parameters (default: none)
...
```

**Comment by Ilpredatore** [comment]
Test1 with: https://github.com/telemaxx/mapsforgesrv/releases/download/v0.19.0_for_java_11/mapsforgesrv-fatjar.jar

MD5: `747b0186dcb9b08f7c094cb1d0c0adad` --> not the same of your

H:\>java -version
```
java version "11.0.18" 2023-01-17 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.18+9-LTS-195)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.18+9-LTS-195, mixed mode)
```

Test Java File:

```
Error: LinkageError occurred while loading main class com.telemaxx.mapsforgesrv.MapsforgeSrv
        java.lang.UnsupportedClassVersionError: com/telemaxx/mapsforgesrv/MapsforgeSrv has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
```
Test2 with: https://github.com/telemaxx/mapsforgesrv/releases/download/v0.18.1_for_java11/mapsforgesrv-fatjar.jar

MD5: `74d978fdd81c80d990a072cad543321f`

Test Java File:

`2023-06-01 11:16:28.212 MapsforgeSrv - a mapsforge tile server. version: 0.18.1
usage: mapsforgesrv
 -c,--config <arg>                   Config file overriding cmd line
                                     parameters (default: none)`

but if i try to launch v.0.18.1 with the last versione of `Mapsforge-for-QMapShack.tcl` i have the previus error version unknown.

Federico

**Comment by JFritzle** [comment]
Please have a look at [https://mkyong.com/java/java-unsupported-class-file-major-version-61](https://mkyong.com/java/java-unsupported-class-file-major-version-61). Class file version 61 means: JAR file has been compiled for Java version 17 or newer.

First:
I am using downloaded file `mapsforgesrv-fatjar.jar` from [https://github.com/telemaxx/mapsforgesrv/raw/master/mapsforgesrv/bin/jars_ready2use/mapsforgesrv-fatjar.jar](https://github.com/telemaxx/mapsforgesrv/raw/master/mapsforgesrv/bin/jars_ready2use/mapsforgesrv-fatjar.jar), which has been compiled for Java 11 (i.e. class file version 55.0). I have also checked file `mapsforgesrv-fatjar.jar` downloaded from [https://github.com/telemaxx/mapsforgesrv/releases/download/v0.19.0_for_java_11/mapsforgesrv-fatjar.jar](https://github.com/telemaxx/mapsforgesrv/releases/download/v0.19.0_for_java_11/mapsforgesrv-fatjar.jar) which obviously has been compiled for Java 17 (i.e. class file version 61). Former one has MD5 hash `0727bd3d73ffcd1ae0c6f9f72379795d`, latter one has MD5 hash `74d978fdd81c80d990a072cad543321f`. Unfortunately, both files differ and the former one is the one that you should use with Java 11.
@telemaxx: Please replace [mapsforgesrv-fatjar.jar](https://github.com/telemaxx/mapsforgesrv/releases/download/v0.19.0_for_java_11/mapsforgesrv-fatjar.jar) for Java 17 by [mapsforgesrv-fatjar.jar](https://github.com/telemaxx/mapsforgesrv/raw/master/mapsforgesrv/bin/jars_ready2use/mapsforgesrv-fatjar.jar) for Java 11.

Second:
When I test latest version of `Mapsforge-for-QMapShack.tcl` with [https://github.com/telemaxx/mapsforgesrv/releases/download/v0.18.1_for_java11/mapsforgesrv-fatjar.jar](https://github.com/telemaxx/mapsforgesrv/releases/download/v0.18.1_for_java11/mapsforgesrv-fatjar.jar) using Java 11 runtime at my site, TCL script does not encounter no error and correctly determines server version to 0.18.1. That's because determination of the server version from server output lines hasn't changed since I don't know when.

**Comment by telemaxx** [comment]
@JFritzle thanks for the investigation!
I had tried the jar inside an vm with java 11. but interesting that I have 2 different jar files, not sure why. I will check, when I am @ home.

**Comment by telemaxx** [comment]
I just uploaded the new jar. via mobile phone, hopefully ok. 😉

**Comment by telemaxx** [comment]
i recreated the jar from eclipse and checked the jar file and it is ok

Some weeks ago i upgraded my Laptop from java 11 to java 17.
Inside Eclipse i set the project target to java 11.
but for some reasons the at the end i got some files for java 17.

How to check(reminder for me)
After unzipping the class files from the jar i entered
`file *.class`

result:

```
DummyCache.class:           compiled Java class data, version 55.0
MapsforgeConfig.class:      compiled Java class data, version 55.0
MapsforgeHandler.class:     compiled Java class data, version 55.0
MapsforgeSrv.class:         compiled Java class data, version 55.0
MapsforgeStyleParser.class: compiled Java class data, version 55.0
```

**Comment by Ilpredatore** [comment]
Hi, 
thank you for you analysis.
But i still have the problem:

![image](https://github.com/telemaxx/mapsforgesrv/assets/22062353/b8ded837-f7eb-442f-9306-2d046a55733d)

I use the last version from: https://github.com/telemaxx/mapsforgesrv/raw/master/mapsforgesrv/bin/jars_ready2use/mapsforgesrv-fatjar.jar

The rusult not change if i try: https://github.com/telemaxx/mapsforgesrv/releases/download/v0.18.1_for_java11/mapsforgesrv-fatjar.jar 

All tested with last version of : https://github.com/JFritzle/Mapsforge-for-QMapShack/blob/main/Mapsforge-for-QMapShack.tcl

Federico

**Comment by telemaxx** [comment]
can you check what happens if you start the server via cmd?

java -jar <path to jar> -m <path to map>

**Comment by Ilpredatore** [comment]
H:\>java -jar "C:\Cartografia\Programmi\Mapsforge-for-QMapShack\mapsforgesrv-fatjar (1).jar" -m C:\Cartografia\Maps
```
2023-06-05 13:40:29.576 MapsforgeSrv - a mapsforge tile server. version: 0.19.0
2023-06-05 13:40:29.579 Java runtime version: 11.0.18
2023-06-05 13:40:29.584 ################## CONFIG INIT ##################
2023-06-05 13:40:29.595 Listening TCP port        : default [8080]
2023-06-05 13:40:29.596 Server interface          : default [localhost]
2023-06-05 13:40:29.601 Map file(s)               : defined [{}]
2023-06-05 13:40:29.601 Theme                     : default [OSMARENDER]
2023-06-05 13:40:29.602 Theme style               : default [null]
2023-06-05 13:40:29.602 Theme overlay(s)          : default [undefined]
2023-06-05 13:40:29.602 Preferred map language    : default [null]
2023-06-05 13:40:29.602 Contrast stretch          : default [0]
2023-06-05 13:40:29.604 Gamma correction          : default [1.0]
2023-06-05 13:40:29.604 Hillshading magnitude     : default [1.0]
2023-06-05 13:40:29.604 DEM                       : default [undefined]
2023-06-05 13:40:29.605 Renderer algorithm        : default [database]
2023-06-05 13:40:29.605 Device scale factor       : default [1.0]
2023-06-05 13:40:29.605 User scale factor         : default [1.0]
2023-06-05 13:40:29.605 Text scale factor         : default [1.0]
2023-06-05 13:40:29.605 Symbol scale factor       : default [1.0]
2023-06-05 13:40:29.606 Browser cache ttl         : default [0]
2023-06-05 13:40:29.606 Out of range TMS url      : default [null]
2023-06-05 13:40:29.606 Append built-in world map : default [false]
2023-06-05 13:40:29.607 Server max queue size     : default [256]
2023-06-05 13:40:29.608 Server max thread(s)      : default [8]
2023-06-05 13:40:29.608 Server min thread(s)      : default [0]
2023-06-05 13:40:29.608 Connection idle timeout   : default [0]
2023-06-05 13:40:29.608 Accept terminate request  : default [false]
2023-06-05 13:40:29.609 Server connector(s)       : default [{http11}]
2023-06-05 13:40:29.804 ################### MAPS INFO ###################
2023-06-05 13:40:29.886 '(built-in)\world.map'
2023-06-05 13:40:29.936 ################ STARTING SERVER ################
2023-06-05 13:40:29.939 jetty-11.0.15; built: 2023-04-11T18:37:53.775Z; git: 5bc5e562c8d05c5862505aebe5cf83a61bdbcb96; jvm 11.0.18+9-LTS-195
2023-06-05 13:40:29.986 Started ServerConnector@4145bad8{HTTP/1.1, (http/1.1, [proxy])}{127.0.0.1:8080}
2023-06-05 13:40:30.008 Started Server@7a35b0f5{STARTING}[11.0.15,sto=0] @678ms
2023-06-05 13:40:30.011 server connector configured with accept queue size '128', idle timeout '0'
2023-06-05 13:40:30.016 job executor configured with threads min '0', max '8', idle timeout '0'
2023-06-05 13:40:30.016 job queue configured with max size '256'
2023-06-05 13:40:30.020 server is up and listening on 'localhost:8080'
```
But this command not open MapsForge for QMapShack GUI.

Federico

**Comment by telemaxx** [comment]
> But this command not open MapsForge for QMapShack GUI.

i know, but it shows the mapsforgesrv is ok so far.

can you try what happens, when you edit the tcl file and deactivate(#) 2 lines like this:

![grafik](https://github.com/telemaxx/mapsforgesrv/assets/22706487/c547456a-90da-418d-9797-cf1757a80964)

should be line 484+485

**Comment by Ilpredatore** [comment]
ok now server starts!

**Comment by JFritzle** [comment]
Commenting these 2 lines is no solution, only a work-around!
If script does not know tile server version, some functionality is missing.

Please test script sent to your private mail address.

**Comment by Ilpredatore** [comment]
> Commenting these 2 lines is no solution, only a work-around! If script does not know tile server version, some functionality is missing.
> 
> Please test script sent to your private mail address.

Yes, something was wrong, infact QMapShack not render the map:

![Render1](https://github.com/telemaxx/mapsforgesrv/assets/22062353/2dd93d0c-da90-4781-9a86-4c5d01ccad75)

**Comment by JFritzle** [comment]
Hi Federico,

still no console output with test script send to [federico.boscarato@gmail.com](mailto:federico.boscarato@gmail.com)?

**Comment by Ilpredatore** [comment]
> Hi Federico,
> 
> still no console output with test script send to [federico.boscarato@gmail.com](mailto:federico.boscarato@gmail.com)?

Hi @JFritzle ,
sorry, but i haven't see your email until now because i find it in spam folder in this moment.
Sorry, i proced with tests.

Federico

**Comment by Ilpredatore** [comment]
I attach a scrrenshot because if i close error windows is also closed output console.

![OutputConsole](https://github.com/telemaxx/mapsforgesrv/assets/22062353/bc6c945a-aff2-4088-b276-9ab1ec5ceb94)

**Comment by Ilpredatore** [comment]
Attached output of test.tcl:

```
test1 command: exec java -version 2>@1
test1 rc: 0
test1 result:


test2 command: open | java -version 2>@1
test2 rc: 0

test3 command: open | java -version 2>@1
test3 rc: 0
test3: java_cmd=java
test3: java_string=unknown
test3: java_version=0
(Mapsforge-for-QMapShack) 1 % 
```

**Comment by JFritzle** [comment]
I wonder, if it as a Java or a Tcl/Tk problem. Please open a `wish` shell by double-clicking `wish.exe` executable and enter following commands into wish console window:
- exec java -version
- exec java.exe -version
- exec {C:\Program Files\Java\jdk-11.0.18\bin\java.exe} -version  
Replace path by path of your java.exe executable

Output should look like this:
![grafik](https://github.com/telemaxx/mapsforgesrv/assets/62614244/bfda3229-31ff-424f-b5b9-3cadcb5de7e5)
If it does not, then I guess it is a Java or Tcl/Tk installation problem at your site.

**Comment by Ilpredatore** [comment]
the result is the following:
```
(bin) 1 % exec java -version

(bin) 2 % exec java.exe -version

(bin) 3 % exec {C:\Program Files\Java\jdk-11\bin\java.exe} -version
java version "11.0.18" 2023-01-17 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.18+9-LTS-195)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.18+9-LTS-195, mixed mode)

(bin) 4 % 
```

**Comment by JFritzle** [comment]
Ok. Commands `java `and `java.exe` within Tcl/Tk obviously do not call executable of your Java installation.
1. Use command `auto_execok java` within wish console to find out what gets called by Tcl/Tk.
Please let me know the result of command.
2. Enter full path of your Java executable into your `Mapsforge-for-QMapShack.ini` file to circumvent problem.

**Comment by Ilpredatore** [comment]
1.
```
 (bin) 1 % auto_execok java

{C:/Program Files/Common Files/Oracle/Java/javapath/java.EXE}

```

2. Must i enter  into my `Mapsforge-for-QMapShack.ini file`?:

- `C:\Program Files\Java\jdk-11\bin\java.exe` 
- `C:/Program Files/Common Files/Oracle/Java/javapath/java.EXE`

I try all two options and it doesn't work.

  Federico

**Comment by JFritzle** [comment]
Please note **comment lines** in ini file:
```
# Important:
# Always use character slash "/" as directory separator in script!
```
-> `C:/Program Files/Java/jdk-11/bin/java.exe` is the correct value to enter into ini file.

As we have seen, `C:/Program Files/Common Files/Oracle/Java/javapath/java.EXE` currently called by Tcl/Tk is not working as expected. Don't ask me why. And I am sorry, it is not possible for me to find the cause remotely. 

At your site, `C:/Program Files/Common Files/Oracle/Java/javapath/java.EXE` seems to point to file `C:/Program Files/Common Files/Oracle/Java/javapath_target_26508703/java.EXE`. The latter one is not the Java executable but a wrapper trying by built-in mechanisms to locate the real Java executable and then redirect call to it. At my site, wrapper is working as expected within TCL script, but not at your site. Might be a matter for Java experts.

**Comment by JFritzle** [comment]
Does it mean, script is now starting without errors and QMapShack is working as expected?

**Comment by Ilpredatore** [comment]
the path in .ini file is correct, but when i try to start app i have the error unknown version.

FILE INI:
```
 set ini_folder    "C:/Cartografia/Programmi/Mapsforge-for-QMapShack"

  set qms_cmd       "C:/Program Files/QMapShack/qmapshack.exe"

  set qms_args      ""

  set maps_folder   "C:/Cartografia/Maps"

  set themes_folder "C:/Cartografia/Styles"

  set java_cmd      "C:/Program Files/Common Files/Oracle/Java/javapath/java.EXE"

  set java_cmd      "java"

  set java_args     ""

  set server_jar    "C:/Cartografia/Programmi/Mapsforge-for-QMapShack/mapsforgesrv-fatjar.jar"
```

**Comment by Ilpredatore** [comment]
> Regarding your ini file: You have 2 assignments to variable `java_cmd`. The second one wins. -> Your script uses command `java` to call Java.
> 
This solve the problem! i Delete variable `java_cmd` and reset previous `java_cmd "C:/Program Files/Java/jdk-11/bin/java.exe"`.
Now Mapsforge-for-QMapShack starts, but QMapShack not render the map:



> ![Render1](https://user-images.githubusercontent.com/22062353/243365904-2dd93d0c-da90-4781-9a86-4c5d01ccad75.JPG)

Federico

**Comment by JFritzle** [comment]
First:
Good news: Java issue got solved. BTW: According to ["java -version" in cmd gives no result](https://stackoverflow.com/questions/65344301/java-versionin-cmd-gives-no-result) is probably caused by value of your Windows variable `PATH`.

Second:
QMapShack does not render map but shows background colour, whenever corners of map window lay outside of map. It's to the user to center the map to desired position. Easiest way: enter e.g. "Palermo" at green magnifying glass at upper right corner when using Italy map.
If it doesn't help, please post console output.

**Comment by Ilpredatore** [comment]
> Second: QMapShack does not render map but shows background colour, whenever corners of map window lay outside of map. It's to the user to center the map to desired position. Easiest way: enter e.g. "Palermo" at green magnifying glass at upper right corner when using Italy map. If it doesn't help, please post console output.

Ok, moving the map, Italy is corret rendered. My mistake because i thought than QMapShack opens rendering and positionig view in current map. Now i proceed to study QMapShack.

Thank you very much!

Federico

**Comment by telemaxx** [comment]
Sounds that the Problems are solved and I can close the ticket.
