### ISSUE TITLE
upgrade gradle and dependencies

### ISSUE THREAD

**Issue by nono303** [telemaxx/mapsforgesrv#5]
Hi @telemaxx!
Thx for this great fork, works like a charm for OpenAndroMaps & Elevate theme.
just give my 2cents patch upgrading gradle and deps.
++NoNo
[mapsforgesrv.patch](https://github.com/telemaxx/mapsforgesrv/files/6932159/mapsforgesrv.patch.txt)

**Comment by telemaxx** [comment]
Hi @nono303 ,
thank you for the patch!
it is now applied to the master branch.

@JFritzle has already updated "his" "java8" branch to gradle 7.0 some month ago.
i have no java8 anymore, so i cant do the patching/testing for the java8 branch
but i think @JFritzle will do the upgrade to gradle 7.1.1 if it is compatible with java8.

Best wishes,
telemaxx
