### ISSUE TITLE
[FR]: Multiple theme rendering

### ISSUE THREAD

**Issue by nono303** [telemaxx/mapsforgesrv#59]
### What is missing?

Hi @telemax,
Currently, I render my map set with 3 different themes (active, elevate, tapiola) and as far as I know I must launch 3 different instances of mapsforgesrv on different port.
My question is: what would be the effort to serve multiple theme (each on a different endpoint) on the same mapsforgesrv instance for the same set of map?
I didn’t dig too much in the code to see how it would be possible and prefer first, taking your advice before contributing ;)

**Comment by nono303** [comment]
Hi @telemaxx,
I also use TCL script from @JFritzle to configure mapsforgesrv but as I know, you cannot expose more than one theme configuration on the same server _(by server I understand a java process instance)_
I don't see this FR so special as you might have this kind of behavior on many maps server which offer different rendering according to activities or usage (bike / hike, winter / summer, detailed / overview...)

#### Here is a concrete use case:
Actually, to serve 4 different rendering theme configurations for one map set, I have to launch 4 java process on different ports 
  :fast_forward: **big memory footprint**
My goal would be to serve them on the same java process with different endpoint
  - http://127.0.0.1:8080/active.hike/z/x/y
  - http://127.0.0.1:8080/active.bike/z/x/y
  - http://127.0.0.1:8080/elevate.hike/z/x/y
  - http://127.0.0.1:8080/active.bike/z/x/y

### My approach _(only works with config file and not cmd line opts)_: 

#### 1.	"cut" the actual config file:
  - One `server.properties`: 
    > renderer, mapfiles, demfolder, interface, port, max-queuesize, min-thread, max-thread, idle-timeout, connectors, cache-control, outofrange_tms, worldmap  
  - 1~n `endpoint.name.properties` in a `/endpoints` folder 
    - _maybe a `default.properties` if only one endpoint to be served on `/`_
    > themefile, style, overlays, language, hillshading-algorithm, hillshading-magnitude, contrast-stretch, gamma-correction, device-scale, user-scale, text-scale, symbol-scale, line-scale  

for my example it would be these 5 files (filename in /endpoint would correspond to path mapped in uri)
```
  - server.properties
  - /endpoints/active.hike.properties 
  - /endpoints/active.bike.properties
  - /endpoints/elevate.hike.properties
  - /endpoints/active.bike.properties
```
#### 2.	Adapt `MapsforgeConfig.java`
  - Keep all server related private vars as it.
  - Move all endpoint related private vars on a new Object `EndpointConfig` and add an new `HashMap<String{@path}, EndpointConfig> Endpoints` private var in `MapsforgeConfig` object
    - Loop over all properties files in `/endpoint` config dir 
    - Check filename (ex. `[a-z_-.]+`) and keep it without extension as the `Endpoints` key
    - And just create an `EndpointConfig` instance with file value mapped to the path as key in `Endpoints` 

#### 3.	Adapt `MapsforgeHandler.java`
  - Big part of the job in constructor: uncouple server & renderer implementation 
    - Server implementation untouched
    - Renderer implementation moved to a new method in `Endpoint` 
  - `handle()` : extract & factorize the `RendererJob`  on `/` and _"mount"_ it on every endpoint configured (with the according `renderThemeFuture`)

ex. in pseudo code:

```
foreach(MapsforgeConfig.getEndpoints. keySet() as endpoint){
	if (path.equals(endpoint)) {
		...
		RendererJob job = new RendererJob(
			tile,								// server related if I understand well
			multiMapDataStore,						// server related: I don't see any interest to have multiple mapset on a same server
			MapsforgeConfig.getEndpoints[endpoint].getRenderThemeFuture,	// according to described changes
			MapsforgeConfig.getEndpoints[endpoint].getDisplayModel,		// according to described changes
			requestedTextScale,						// uri parameter related
			requestedTransparent,						// uri parameter related
			false
		);
	}
}
```

I'll try to implement it but my Java is quite rusty (last dev was on a Sun VM ^^) 
So before spending time there, I would be delighted to have @telemaxx & @JFritzle feedback on this approach.
++NoNo

**Comment by JFritzle** [comment]
I'm sorry, but my Java skills are weak. Only had C/C++ knowledge but no Java experience at all before joining to _mapsforgesrv_ project. Therefore, I'm afraid I won't be able to contribute until a basic solution is implemented.

**Comment by telemaxx** [comment]
Sound, like we have the same java skills ;-)

Sometimes i combine bike and hike themes.
This is possible because the bike themes eg from OAM also have some hiking parts included in the bike theme.

At the moment i have not the time to help programming this feature,
but if you send a PR, i can merge.

The code should stay should stay slim and easy to maintain.

**Comment by nono303** [comment]
Hi,
I'd reviewed my approach with a real java boy ;) and I kept in mind that final usage must not change according to other apps using mapsforgesrv 
so, exit the endpoint concept, welcome to the style url param!

:fast_forward: https://github.com/nono303/mapsforgesrv/tree/styles

### Keypoints
- functional code had not been changed _(except some cleaning or feature adding)_
- usage had not changed: no functional regression
  - just adding a new optional url parameter 'style'
- configuration had changed: All must be done by files with only `-c` arg defining the root 'config directory'
  - `./jetty.xml`: Jetty is now configured based on a single and [standard xml file](https://github.com/jetty/jetty.project/blob/jetty-11.0.x/jetty-server/src/main/config/etc/jetty-http.xml)
  - `./server.properties`: same as original without theme related properties
  - `/styles/default.properties`: only (and all) theme related properties
    - might be empty but must be present (to be discussed ;)
  - `/styles/([0-9a-z._-]+).properties` for all desired styles (filename same as style url param)
### DONE
- **`MapsforgeSrv`**
  - removed all code & properties related to Jetty server configuration
    - it'll allow to set various tunning option and adapt http severing to any usage without changing code!
- **`MapsforgeConfig`**
  - removed all properties related to Jetty (also in config file...)
  - extracted theme configuration related properties to `MapsforgeStyleConfig`
    - added `private Map<String, MapsforgeStyleConfig> styles`;
  - factorized common functions for `MapsforgeConfig` & `MapsforgeStyleConfig` to `PropertiesParser`
- **`MapsforgeHandler`**
  - extracted theme rendering related properties to `MapsforgeStyleHandler`
    - add `private Map<String, MapsforgeStyleHandler> stylesHandler`
    - load extra style only if `!hillShadingOverlay`
- **Misc**
  - tried to improve startup and request logs
  - cleaned typo, unused & few duplicate
  - refactored in `PropertiesParser`, comment and standardize name for default & static value 
  - `/updatemapstyle`: html display of updated styles
  - `updateRenderThemeFuture()`: interrupt previous RenderThemeFuture thread if exist _(i checked and see multiple thread after multiple reload)
  - 'config directory': update & add comment for mandatory & example files
  - Performance
    - set `MemoryCachingHgtReaderTileSource` with `mainCacheSize` & `neighborCacheSize`
    - enabled Virtual threads JRE >= 21 only
    - made ~100k hillshading tile requests test simultaneously on 5 different styles without constating any memory leak 
### TO BE VERIFEID
- that properties like `tileCache`, `labelStore`, `displayModel`, `colorLookupTable`... are really specific for `MapsforgeStyleHandler` (and not `MapsforgeHandler`)
  - Ex. `tileCache`: I don't really understand what are or might be stored in that...
    - if it's raw data from `MultiMapDataStore`, it must be instanced once in `MapsforgeHandler`
    - if's it's theme rendered data, it must set as it, in `MapsforgeStyleHandler`
  - gamma correction and/or contrast-stretching (had made just a quick visual validation...)
### TO BE CLARIFIED
- **`TileCache`**
  - Why [`DummyCache`](https://github.com/telemaxx/mapsforgesrv/blob/master/mapsforgesrv/src/main/java/com/telemaxx/mapsforgesrv/MapsforgeHandler.java#L205) vs. [InMemoryTileCache](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-map/src/main/java/org/mapsforge/map/layer/cache/InMemoryTileCache.java)?
    - What the purpose of [`(!hillShadingOverlay) tileCache.put(job, null)`](https://github.com/telemaxx/mapsforgesrv/blob/master/mapsforgesrv/src/main/java/com/telemaxx/mapsforgesrv/MapsforgeHandler.java#L529) _(which cause exception implementing `InMemoryTileCache`)_
- **`DisplayModel`**
  - why some [static settings]() 
  - why `updateRenderThemeFuture() if [displayModel.getUserScaleFactor() != requestedUserScale](https://github.com/telemaxx/mapsforgesrv/blob/master/mapsforgesrv/src/main/java/com/telemaxx/mapsforgesrv/MapsforgeHandler.java#L514)`
### TODO
- documentation
- maybe a better way to manage `databaseRenderer` / `directRenderer` as only one can be instantiated
- and… add VTM renderer ^^

I'll let you have a look and give me your feeling on that before making a PR as it might be too disruptive to be merged and kept as a fork

![Clipboard_05-23-2024_01](https://github.com/telemaxx/mapsforgesrv/assets/2869665/e32668e1-0d30-4a38-b46b-2bf30d145382)

**Comment by telemaxx** [comment]
Thank you for you're work.

As you said, it is important that are no breaking changes. Other software should still run without changes.
you're new approach looks good.

i created a new branch [nono303](https://github.com/telemaxx/mapsforgesrv/tree/nono303)
when i try to send me a PR from you're fork in this new branch i got conflicts.
i have not investigated why.

Can you send me a PR in this branch?
Than i can build, compare and test.

BTW: i like the style of you're posts. easy to read.

**Comment by nono303** [comment]
https://github.com/telemaxx/mapsforgesrv/pull/63
BTW: U'll find references of used theme in [style properties file](https://github.com/nono303/mapsforgesrv/tree/styles/mapsforgesrv/config/styles) l.6

**Comment by JFritzle** [comment]
Tried recent `mapsforgesrv-fatjar.jar` from @nono303 repository.

`"<java path>/jdk-22.0.2/bin/java.exe -jar" "<jar path>/mapsforgesrv-fatjar.jar" -h` gives 
```
SLF4J(I): Connected with provider of type [org.slf4j.reload4j.Reload4jServiceProvider]
2024-07-30 12:46:43.938 main@MapsforgeSrv:83 - MapsforgeSrv - a mapsforge tile server. version: 0.21.3.0
2024-07-30 12:46:43.939 main@MapsforgeSrv:85 - Java runtime version: 22.0.2
2024-07-30 12:46:43.953 main@MapsforgeConfig:67 - Unrecognized option: -h
usage: mapsforgesrv
 -c,--config <arg>   Config directory including at least server.properties, jetty.xml, styles/default.properties
```

`"<java path>/jdk-22.0.2/bin/java.exe -jar" "<jar path>/mapsforgesrv-fatjar.jar"` gives 
```
SLF4J(I): Connected with provider of type [org.slf4j.reload4j.Reload4jServiceProvider]
2024-07-30 12:54:00.572 main@MapsforgeSrv:83 - MapsforgeSrv - a SLF4J(I): Connected with provider of type [org.slf4j.reload4j.Reload4jServiceProvider]
2024-07-30 12:54:00.572 main@MapsforgeSrv:83 - MapsforgeSrv - a mapsforge tile server. version: 0.21.3.0
2024-07-30 12:54:00.574 main@MapsforgeSrv:85 - Java runtime version: 22.0.2
2024-07-30 12:54:00.587 main@MapsforgeConfig:67 - Missing required option: c
usage: mapsforgesrv
 -c,--config <arg>   Config directory including at least server.properties, jetty.xml, styles/default.properties: 0.21.3.0
```

How to query this mapsforge tile server's version and get version in **output line 1** without succeeding error messages like with all mapsforge tile server versions before?

**Comment by telemaxx** [comment]
completed in new tasks branch.

[renamed](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch) styles branch to tasks
